export enum AuthConstants { 
  AUTH_INIT = "AUTH_INIT",

  AUTH_LOGIN = "AUTH_LOGIN",
  AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED",

  AUTH_REGISTER = "AUTH_LOGIN",
  AUTH_REGISTER_SUCCESS = "AUTH_LOGIN_SUCCESS",
  AUTH_REGISTER_FAILED = "AUTH_LOGIN_FAILED",

  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS",

  AUTH_DATA_EXTRACT = "AUTH_DATA_EXTRACT",
}

export enum Endpoints {
  Login = 'auth/login'
}