export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_POPULAR_NEWS_REQUEST = "FETCH_POPULAR_NEWS_REQUEST";
// export const FETCH_ALL_NEWS_REQUEST = "FETCH_ALL_NEWS_REQUEST";


export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_POPULAR_NEWS_SUCCESS = "FETCH_POPULAR_NEWS_SUCCESS";

export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
export const FETCH_POPULAR_NEWS_FAILURE = "FETCH_POPULAR_NEWS_FAILURE";
